#!/bin/sh
for i in $(find examples -type f | grep -v "\.svn" | sort)
do
	echo "Test de '$i':"
	cat $i
	echo "================="
	./compilo < "$i" > tmp &&
	spim -file tmp | tail -n1
	echo "================="
	echo ""
done
rm tmp
